import mysql.connector
from mysql.connector import errorcode
print("ok")
try:
 cnx = mysql.connector.connect(user='root', password='HARDWARE',
                               host='127.0.0.1',
                               database='weather_data')

 cur = cnx.cursor()

 query = "LOAD DATA LOCAL INFILE 'C:/Users/ajayj/Google Drive/MasterThesis/Database/kmds_alle_stations_10001_201611290900.dat' INTO TABLE loaddata CHARACTER SET UTF8 FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n' (station_id,date_num,time_num,timestep,data_code,@vvalue_var,extra_var) SET value_var = nullif(@vvalue_var,'') "
 cur.execute(query)
 cnx.commit()

except mysql.connector.Error as err:
  if err.errno == errorcode.ER_ACCESS_DENIED_ERROR:
    print("Something is wrong with your user name or password")
  elif err.errno == errorcode.ER_BAD_DB_ERROR:
    print("Database does not exist")
  else:
    print(err)
else:
  cnx.close()
